// Static data for S3 hosting - no server dependencies
export const staticData = {
  schoolInfo: {
    name: 'Jankalyan Nivasi Vidyalay',
    location: 'Latur, Maharashtra',
    established: 1993,
    affiliation: 'SSC Board',
    classes: 'V to X',
    students: 580,
    faculty: 45,
    phone: '+91 95959 77224',
    email: 'principal@jnvlatur.edu.in',
    address: 'Harangul Bu., District Latur, Maharashtra',
  },
  newsItems: [
    {
      id: '1',
      title: 'Admission Process for Academic Year 2024-25',
      description: 'Online registration for Class VI admissions begins from January 15, 2024. All eligible candidates can apply through the official portal.',
      date: '2024-01-10',
      type: 'announcement' as const,
      category: 'Admissions',
    },
    {
      id: '2',
      title: 'Annual Science Exhibition 2024',
      description: 'Students showcase innovative science projects at the annual exhibition. Prize distribution ceremony on January 25, 2024.',
      date: '2024-01-08',
      type: 'event' as const,
      category: 'Academic',
    },
    {
      id: '3',
      title: 'Class X Board Results 2023-24',
      description: 'Excellent performance with 98.5% pass rate. School topper achieves 97.8% marks in SSC Board examination.',
      date: '2024-01-05',
      type: 'result' as const,
      category: 'Results',
    },
  ],
  achievements: [
    {
      id: '1',
      title: 'National Athletics Championship Bronze Medal',
      description: 'Student secured bronze medal in 400m sprint at national level athletics championship.',
      level: 'national' as const,
      category: 'sports' as const,
      year: 2023,
      award: 'Bronze Medal',
    },
    {
      id: '2',
      title: 'State Cricket Champions 2023',
      description: 'School cricket team won the state level championship defeating teams from across Maharashtra.',
      level: 'state' as const,
      category: 'sports' as const,
      year: 2023,
      award: 'Champions Trophy',
    },
    {
      id: '3',
      title: 'Science Exhibition First Prize',
      description: 'Students won first prize at regional science exhibition for innovative water purification project.',
      level: 'state' as const,
      category: 'science' as const,
      year: 2023,
      award: 'First Prize',
    },
  ],
  facultyMembers: [
    {
      id: '1',
      name: 'Mr. Sonttake Sir',
      designation: 'Principal',
      subject: 'Education Administration',
      qualification: 'Ph.D. in Education',
      experience: 25,
      image: '/images/HeadMaster.jpg',
    },
    {
      id: '2',
      name: 'Mrs. Rekha Ma\'am',
      designation: 'Vice Principal',
      subject: 'Educational Psychology',
      qualification: 'M.Ed.',
      experience: 20,
      image: '/images/RekhaMaam.jpg',
    },
    {
      id: '3',
      name: 'Mr. Patil Sir',
      designation: 'Academic Coordinator',
      subject: 'Mathematics',
      qualification: 'M.Sc. Mathematics',
      experience: 18,
      image: '/images/PatilSir.jpg',
    },
    {
      id: '4',
      name: 'Mr. Kale Sir',
      designation: 'Administrative Officer',
      subject: 'Education Management',
      qualification: 'MBA in Education Management',
      experience: 15,
      image: '/images/KaleSir.jpg',
    },
    {
      id: '5',
      name: 'Mr. Babalsure Sir',
      designation: 'Hostel Warden',
      subject: 'History',
      qualification: 'M.A. History, B.Ed.',
      experience: 12,
      image: '/images/HostelWardon.jpg',
    },
  ],
  galleryItems: [
    {
      id: '1',
      title: 'Modern Classrooms',
      description: 'Well-equipped classrooms with modern teaching aids and comfortable seating.',
      image: '/images/Classroom1.jpg',
      category: 'campus' as const,
    },
    {
      id: '2',
      title: 'Science Laboratory',
      description: 'State-of-the-art science laboratory for practical experiments and research.',
      image: '/images/ScienceLaboratory.jpg',
      category: 'campus' as const,
    },
    {
      id: '3',
      title: 'Computer Laboratory',
      description: 'Modern computer lab with latest technology for digital learning.',
      image: '/images/ComputerLab.jpg',
      category: 'campus' as const,
    },
    {
      id: '4',
      title: 'Central Library',
      description: 'Spacious library with extensive collection of books and digital resources.',
      image: '/images/Library.jpg',
      category: 'campus' as const,
    },
    {
      id: '5',
      title: 'Academic Buildings',
      description: 'Beautiful academic buildings providing an excellent learning environment.',
      image: '/images/Acadmics_building1.jpg',
      category: 'campus' as const,
    },
    {
      id: '6',
      title: 'Sports Ground',
      description: 'Large playground for various sports activities and physical education.',
      image: '/images/ground1.jpg',
      category: 'activities' as const,
    },
    {
      id: '7',
      title: 'Assembly Hall',
      description: 'Spacious assembly hall for school gatherings and cultural events.',
      image: '/images/Assembly.jpg',
      category: 'events' as const,
    },
    {
      id: '8',
      title: 'Cultural Events',
      description: 'Students participating in various cultural activities and competitions.',
      image: '/images/Culture.jpg',
      category: 'cultural' as const,
    },
    {
      id: '9',
      title: 'Morning Exercise',
      description: 'Students performing morning exercises and physical activities.',
      image: '/images/Exercise.jpg',
      category: 'activities' as const,
    },
    {
      id: '10',
      title: 'Study Sessions',
      description: 'Students engaged in focused study sessions in the library.',
      image: '/images/Study.jpg',
      category: 'campus' as const,
    },
    {
      id: '11',
      title: 'Teachers Meeting',
      description: 'Faculty members in discussion and planning sessions.',
      image: '/images/Teachers.jpg',
      category: 'events' as const,
    },
    {
      id: '12',
      title: 'Parent-Teacher Meeting',
      description: 'Regular interactions between parents and teachers for student development.',
      image: '/images/ParentsMeet.jpg',
      category: 'events' as const,
    },
  ],
  contactInfo: {
    office: '+91 95959 77224',
    principal: '+91 95959 77224',
    admissions: '+91 95959 77224',
    email: {
      general: 'principal@jnvlatur.edu.in',
      principal: 'principal@jnvlatur.edu.in',
      admissions: 'principal@jnvlatur.edu.in',
    },
    address: {
      street: 'Jankalyan Nivasi Vidyalay',
      village: 'Harangul Bu.',
      taluka: '',
      district: 'District Latur',
      state: 'Maharashtra',
      pincode: '413531',
    },
    hours: {
      weekdays: '9:00 AM - 5:00 PM',
      saturday: '9:00 AM - 1:00 PM',
      sunday: 'Closed',
    },
  },
  historicalResults: [
    { year: '1995-96', percentage: 26 },
    { year: '1996-97', percentage: 55.26 },
    { year: '1997-98', percentage: 71.05 },
    { year: '1998-99', percentage: 56.41 },
    { year: '1999-2000', percentage: 71.42 },
    { year: '2000-2001', percentage: 93.93 },
    { year: '2001-2002', percentage: 88.57 },
    { year: '2002-2003', percentage: 97.93 },
    { year: '2003-2004', percentage: 97.14 },
    { year: '2004-2005', percentage: 96.49 },
    { year: '2005-2006', percentage: 88.57 },
    { year: '2006-2007', percentage: 100 },
    { year: '2007-2008', percentage: 91.66 },
    { year: '2008-2009', percentage: 100 },
    { year: '2009-2010', percentage: 98.55 },
    { year: '2010-2011', percentage: 97.46 },
    { year: '2011-2012', percentage: 93.75 },
    { year: '2012-2013', percentage: 100 },
    { year: '2013-2014', percentage: 100 },
    { year: '2014-2015', percentage: 100 },
    { year: '2015-2016', percentage: 97 },
    { year: '2016-2017', percentage: 100 },
    { year: '2017-2018', percentage: 98.5 },
    { year: '2018-2019', percentage: 99.2 },
    { year: '2019-2020', percentage: 96.8 },
    { year: '2020-2021', percentage: 97.5 },
    { year: '2021-2022', percentage: 98.9 },
    { year: '2022-2023', percentage: 99.1 },
    { year: '2023-2024', percentage: 97.8 },
  ],
};

